export default {
  row1: {
    1: {
      lang1: '`',
      key: 'Backquote',
      lang1: '`',
      lang2: '`',
      shift1: '¬',
      shift2: '~',
      altGr1: '¦',
      altGr2: null,
      shiftAltGr1: null,
    },
    2: {
      lang1: '1',
      key: 'Digit1',
      lang1: '1',
      lang2: 'Ą',
      shift1: '!',
      shift2: '1',
      altGr1: null,
      altGr2: '1',
      shiftAltGr2: null,
    },
    3: {
      lang1: '2',
      key: 'Digit2',
      lang1: '2',
      lang2: 'Č',
      shift1: '"',
      shift2: null,
      altGr1: null,
      altGr2: '2',
      shiftAltGr2: '@',
    },
    4: {
      key: 'Digit3',
      lang1: '3',
      lang2: 'Ę',
      shift1: '£',
      shift2: null,
      altGr1: null,
      altGr2: '3',
      shiftAltGr2: '#',
    },
    5: {
      key: 'Digit4',
      lang1: '4',
      lang2: 'Ė',
      shift1: '$',
      shift2: null,
      altGr1: '€',
      altGr2: '4',
      shiftAltGr2: '$',
    },
    6: {
      key: 'Digit5',
      lang1: '5',
      lang2: 'Į',
      shift1: '%',
      shift2: null,
      altGr1: null,
      altGr2: '5',
      shiftAltGr2: '%',
    },
    7: {
      key: 'Digit6',
      lang1: '6',
      lang2: 'Š',
      shift1: '^',
      shift2: null,
      altGr1: null,
      altGr2: '6',
      shiftAltGr2: '^',
    },
    8: {
      key: 'Digit7',
      lang1: '7',
      lang2: 'Ų',
      shift1: '&',
      shift2: null,
      altGr1: null,
      altGr2: '7',
      shiftAltGr2: '&',
    },
    9: {
      key: 'Digit8',
      lang1: '8',
      lang2: 'Ū',
      shift1: '*',
      shift2: null,
      altGr: null,
      altGr2: '8',
      shiftAltGr2: '*',
    },
    10: {
      lang1: '9',
      lang2: '9',
      key: 'Digit9',
      shift1: '(',
      shift2: '(',
      altGr: null,
      shiftAltGr1: null,
    },
    11: {
      lang1: '0',
      lang2: '0',
      key: 'Digit0',
      shift1: ')',
      shift2: ')',
      altGr1: null,
      altGr2: null,
      shiftAltGr1: null,
    },
    12: {
      key: 'Minus',
      lang1: '-',
      lang2: '-',
      shift1: '_',
      shift2: '_',
      altGr1: null,
      altGr2: null,
      shiftAltGr1: null,
    },
    13: {
      key: 'Equal',
      lang1: '=',
      lang2: 'Ž',
      shift1: '+',
      shift2: null,
      altGr1: null,
      altGr2: '=',
      shiftAltGr2: '+',
    },
    14: { colspan: 1.6, main: 'Bksp', key: 'Backspace' },
  },

  row2: {
    1: {
      main: 'Tab',
      key: 'Tab',
      colspan: 1.6,
    },
    2: {
      lang1: 'Q',
      lang2: 'Q',
      key: 'KeyQ',
    },
    3: {
      lang1: 'W',
      lang2: 'W',
      key: 'KeyW',
    },
    4: {
      lang1: 'E',
      lang2: 'E',
      key: 'KeyE',
      shift2: ' ',
      altGr2: '€',
    },
    5: {
      lang1: 'R',
      lang2: 'R',
      key: 'KeyR',
    },
    6: {
      lang1: 'T',
      lang2: 'T',
      key: 'KeyT',
    },
    7: {
      lang1: 'Y',
      lang2: 'Y',
      key: 'KeyY',
    },
    8: {
      lang1: 'U',
      lang2: 'U',
      key: 'KeyU',
    },
    9: {
      lang1: 'I',
      lang2: 'I',
      key: 'KeyI',
    },
    10: {
      lang1: 'O',
      lang2: 'O',
      key: 'KeyO',
    },
    11: {
      lang1: 'P',
      lang2: 'P',
      key: 'KeyP',
    },
    12: {
      lang1: '[',
      lang2: '[',
      key: 'BracketLeft',
      shift1: '{',
      shift2: '{',
    },
    13: {
      lang1: ']',
      lang2: ']',
      key: 'BracketRight',
      shift1: '}',
      shift2: '}',
    },
    14: { lang1: 'Del', lang2: 'Del', key: 'Delete' },
  },

  row3: {
    1: {
      main: 'Caps',
      key: 'CapsLock',
    },
    2: {
      lang1: 'A',
      lang2: 'A',
      key: 'KeyA',
    },
    3: {
      lang1: 'S',
      lang2: 'S',
      key: 'KeyS',
    },
    4: {
      lang1: 'D',
      lang2: 'D',
      key: 'KeyD',
    },
    5: {
      lang1: 'F',
      lang2: 'F',
      key: 'KeyF',
    },
    6: {
      lang1: 'G',
      lang2: 'G',
      key: 'KeyG',
    },
    7: {
      lang1: 'H',
      lang2: 'H',
      key: 'KeyH',
    },
    8: {
      lang1: 'J',
      lang2: 'J',
      key: 'KeyJ',
    },
    9: {
      lang1: 'K',
      lang2: 'K',
      key: 'KeyK',
    },
    10: {
      lang1: 'L',
      lang2: 'L',
      key: 'KeyL',
    },
    11: {
      lang1: ';',
      lang2: ';',
      key: 'Semicolon',
      shift1: ':',
      shift2: ':',
    },
    12: {
      lang1: "'",
      lang2: "'",
      key: 'Quote',
      shift1: '@',
      shift2: '"',
    },
    13: {
      lang1: '#',
      lang2: '\\',
      key: 'Backslash',
      shift1: '~',
      shift2: '|',
    },
    14: { colspan: 1.6, lang1: 'Enter', lang2: 'Enter', key: 'Enter' },
  },
  row4: {
    1: {
      main: 'Shift',
      key: 'ShiftLeft',
      colspan: 1.6,
    },
    2: {
      lang1: '\\',
      lang2: '\\',
      key: 'IntlBackslash',
      shift1: '|',
      shift2: '|',
    },
    3: {
      lang1: 'Z',
      lang2: 'Z',
      key: 'KeyZ',
    },
    4: {
      lang1: 'X',
      lang2: 'X',
      key: 'KeyX',
    },
    5: {
      lang1: 'C',
      lang2: 'C',
      key: 'KeyC',
    },
    6: {
      lang1: 'V',
      lang2: 'V',
      key: 'KeyV',
    },
    7: {
      lang1: 'B',
      lang2: 'B',
      key: 'KeyB',
    },
    8: {
      lang1: 'N',
      lang2: 'N',
      key: 'KeyN',
    },
    9: {
      lang1: 'M',
      lang2: 'M',
      key: 'KeyM',
    },
    10: {
      lang1: ',',
      lang2: ',',
      key: 'Comma',
      shift1: '<',
      shift2: '<',
    },
    11: {
      lang1: '.',
      lang2: '.',
      key: 'Period',
      shift1: '>',
      shift2: '>',
    },
    12: {
      lang1: '/',
      lang2: '/',
      key: 'Slash',
      shift1: '?',
      shift2: '?',
    },
    13: {
      main: '↑',
      key: 'ArrowUp',
    },
    14: {
      main: 'Shift',
      key: 'ShiftRight',
    },
  },
  row5: {
    1: {
      main: 'Ctrl',
      key: 'ControlLeft',
    },
    2: {
      main: 'Win',
      key: 'MetaLeft',
    },
    3: {
      main: 'Alt',
      key: 'AltLeft',
    },
    4: {
      main: 'Space',
      key: 'Space',
      colspan: 7.3,
    },
    5: {
      main: 'AltGr',
      key: 'AltRight',
      colspan: 1.5,
    },
    6: {
      main: 'Ctrl',
      key: 'ControlRight',
    },
    7: {
      main: '←',
      key: 'ArrowLeft',
    },
    8: {
      main: '↓',
      key: 'ArrowDown',
    },
    9: {
      main: '→',
      key: 'ArrowRight',
    },
  },
};
