export default {
  row1: {
    1: {
      lang1: '`',
      key: 'Backquote',
      lang1: '`',
      lang2: '`',
      shift1: '¬',
      shift2: '~',
      altGr1: '¦',
      altGr2: null,
      shiftAltGr1: null,
    },
    2: {
      key: 'Digit1',
      lang1: '1',
      lang2: 'ą',
      shift1: '!',
      shift2: null,
      altGr1: null,
      altGr2: '1',
      shiftAltGr2: '!',
    },
    3: {
      key: 'Digit2',
      lang1: '2',
      lang2: 'č',
      shift1: '"',
      shift2: null,
      altGr1: null,
      altGr2: '2',
      shiftAltGr2: '@',
    },
    4: {
      key: 'Digit3',
      lang1: '3',
      lang2: 'ę',
      shift1: '£',
      shift2: null,
      altGr1: null,
      altGr2: '3',
      shiftAltGr2: '#',
    },
    5: {
      key: 'Digit4',
      lang1: '4',
      lang2: 'ė',
      shift1: '$',
      shift2: null,
      altGr1: '€',
      altGr2: '4',
      shiftAltGr2: '$',
    },
    6: {
      key: 'Digit5',
      lang1: '5',
      lang2: 'į',
      shift1: '%',
      shift2: null,
      altGr1: null,
      altGr2: '5',
      shiftAltGr2: '%',
    },
    7: {
      key: 'Digit6',
      lang1: '6',
      lang2: 'š',
      shift1: '^',
      shift2: null,
      altGr1: null,
      altGr2: '6',
      shiftAltGr2: '^',
    },
    8: {
      key: 'Digit7',
      lang1: '7',
      lang2: 'Ų',
      shift1: '&',
      shift2: null,
      altGr1: null,
      altGr2: '7',
      shiftAltGr2: '&',
    },
    9: {
      key: 'Digit8',
      lang1: '8',
      lang2: 'Ū',
      shift1: '*',
      shift2: null,
      altGr: null,
      altGr2: '8',
      shiftAltGr2: '*',
    },
    10: {
      lang1: '9',
      lang2: '9',
      key: 'Digit9',
      shift1: '(',
      shift2: '(',
      altGr: null,
      shiftAltGr1: null,
    },
    11: {
      lang1: '0',
      lang2: '0',
      key: 'Digit0',
      shift1: ')',
      shift2: ')',
      altGr1: null,
      altGr2: null,
      shiftAltGr1: null,
    },
    12: {
      key: 'Minus',
      lang1: '-',
      lang2: '-',
      shift1: '_',
      shift2: '_',
      altGr1: null,
      altGr2: null,
      shiftAltGr1: null,
    },
    13: {
      key: 'Equal',
      lang1: '=',
      lang2: 'ž',
      shift1: '+',
      shift2: null,
      altGr1: null,
      altGr2: '=',
      shiftAltGr2: '+',
    },
    14: { colspan: 1.6, main: 'Bksp', key: 'Backspace' },
  },

  row2: {
    1: {
      main: 'Tab',
      key: 'Tab',
      colspan: 1.6,
    },
    2: {
      lang1: 'q',
      lang2: 'q',
      key: 'KeyQ',
    },
    3: {
      lang1: 'w',
      lang2: 'w',
      key: 'KeyW',
    },
    4: {
      lang1: 'e',
      lang2: 'e',
      key: 'KeyE',
      shift2: ' ',
      altGr2: '€',
    },
    5: {
      lang1: 'r',
      lang2: 'r',
      key: 'KeyR',
    },
    6: {
      lang1: 't',
      lang2: 't',
      key: 'KeyT',
    },
    7: {
      lang1: 'y',
      lang2: 'y',
      key: 'KeyY',
    },
    8: {
      lang1: 'u',
      lang2: 'u',
      key: 'KeyU',
    },
    9: {
      lang1: 'i',
      lang2: 'i',
      key: 'KeyI',
    },
    10: {
      lang1: 'o',
      lang2: 'o',
      key: 'KeyO',
    },
    11: {
      lang1: 'p',
      lang2: 'p',
      key: 'KeyP',
    },
    12: {
      lang1: '[',
      lang2: '[',
      key: 'BracketLeft',
      shift1: '{',
      shift2: '{',
    },
    13: {
      lang1: ']',
      lang2: ']',
      key: 'BracketRight',
      shift1: '}',
      shift2: '}',
    },
    14: { main: 'Del', key: 'Delete' },
  },

  row3: {
    1: {
      main: 'Caps',
      key: 'CapsLock',
    },
    2: {
      lang1: 'a',
      lang2: 'a',
      key: 'KeyA',
    },
    3: {
      lang1: 's',
      lang2: 's',
      key: 'KeyS',
    },
    4: {
      lang1: 'd',
      lang2: 'd',
      key: 'KeyD',
    },
    5: {
      lang1: 'f',
      lang2: 'f',
      key: 'KeyF',
    },
    6: {
      lang1: 'g',
      lang2: 'g',
      key: 'KeyG',
    },
    7: {
      lang1: 'h',
      lang2: 'h',
      key: 'KeyH',
    },
    8: {
      lang1: 'j',
      lang2: 'j',
      key: 'KeyJ',
    },
    9: {
      lang1: 'k',
      lang2: 'k',
      key: 'KeyK',
    },
    10: {
      lang1: 'l',
      lang2: 'l',
      key: 'KeyL',
    },
    11: {
      lang1: ';',
      lang2: ';',
      key: 'Semicolon',
      shift1: ':',
      shift2: ':',
    },
    12: {
      lang1: "'",
      lang2: "'",
      key: 'Quote',
      shift1: '@',
      shift2: '"',
    },
    13: {
      lang1: '#',
      lang2: '\\',
      key: 'Backslash',
      shift1: '~',
      shift2: '|',
    },
    14: { colspan: 1.6, main: 'Enter', key: 'Enter' },
  },
  row4: {
    1: {
      main: 'Shift',
      key: 'ShiftLeft',
      colspan: 1.6,
    },
    2: {
      lang1: '\\',
      lang2: '\\',
      key: 'IntlBackslash',
      shift1: '|',
      shift2: '|',
    },
    3: {
      lang1: 'z',
      lang2: 'z',
      key: 'KeyZ',
    },
    4: {
      lang1: 'x',
      lang2: 'x',
      key: 'KeyX',
    },
    5: {
      lang1: 'c',
      lang2: 'c',
      key: 'KeyC',
    },
    6: {
      lang1: 'v',
      lang2: 'v',
      key: 'KeyV',
    },
    7: {
      lang1: 'b',
      lang2: 'b',
      key: 'KeyB',
    },
    8: {
      lang1: 'n',
      lang2: 'n',
      key: 'KeyN',
    },
    9: {
      lang1: 'm',
      lang2: 'm',
      key: 'KeyM',
    },
    10: {
      lang1: ',',
      lang2: ',',
      key: 'Comma',
      shift1: '<',
      shift2: '<',
    },
    11: {
      lang1: '.',
      lang2: '.',
      key: 'Period',
      shift1: '>',
      shift2: '>',
    },
    12: {
      lang1: '/',
      lang2: '/',
      key: 'Slash',
      shift1: '?',
      shift2: '?',
    },
    13: {
      main: '↑',
      key: 'ArrowUp',
    },
    14: {
      main: 'Shift',
      key: 'ShiftRight',
    },
  },
  row5: {
    1: {
      main: 'Ctrl',
      key: 'ControlLeft',
    },
    2: {
      main: 'Win',
      key: 'MetaLeft',
    },
    3: {
      main: 'Alt',
      key: 'AltLeft',
    },
    4: {
      main: 'Space',
      key: 'Space',
      colspan: 7.3,
    },
    5: {
      main: 'AltGr',
      key: 'AltRight',
      colspan: 1.5,
    },
    6: {
      main: 'Ctrl',
      key: 'ControlRight',
    },
    7: {
      main: '←',
      key: 'ArrowLeft',
    },
    8: {
      main: '↓',
      key: 'ArrowDown',
    },
    9: {
      main: '→',
      key: 'ArrowRight',
    },
  },
};
